const fs = require('fs');
const path = require('path');

const baseDir = path.join('c:', 'Users', 'being', 'Downloads', 'gift-box');
const srcDir = path.join(baseDir, 'src');
const appDir = path.join(srcDir, 'app');
const pagesDir = path.join(srcDir, 'pages');

const dirsToCreate = [
    "app/(auth)/login",
    "app/(auth)/register",
    "app/(auth)/forgot-password",
    "app/(auth)/change-password",
    "app/(auth)/verify-otp",
    "app/(website)/about",
    "app/(website)/faq",
    "app/(website)/support",
    "app/(website)/terms",
    "app/(website)/privacy",
    "app/(website)/language",
    "app/(dashboard)/profile/edit",
    "app/(dashboard)/my-draws",
    "app/(dashboard)/draws/[id]",
    "app/(dashboard)/results",
    "app/(dashboard)/participation/[id]",
    "app/(dashboard)/payment-proof",
    "app/api/auth",
    "components/ui",
    "components/shared",
    "components/forms",
    "lib",
    "utils",
    "hooks",
    "context",
    "services",
    "store",
    "types"
];

// Create dirs
dirsToCreate.forEach(d => {
    fs.mkdirSync(path.join(srcDir, d), { recursive: true });
});

// Delete files
const filesToDelete = [
    "vite.config.ts",
    "index.html",
    "tsconfig.node.json",
    "tsconfig.app.json",
    path.join("src", "main.tsx"),
];

filesToDelete.forEach(f => {
    const p = path.join(baseDir, f);
    if (fs.existsSync(p)) {
        fs.unlinkSync(p);
    }
});

// Layout
const layoutCode = `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Gift Box App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`;
fs.writeFileSync(path.join(appDir, "layout.tsx"), layoutCode, "utf8");

// Rename CSS
const oldCss = path.join(srcDir, "index.css");
const newCss = path.join(appDir, "globals.css");
if (fs.existsSync(oldCss)) {
    fs.renameSync(oldCss, newCss);
}

const pageMap = {
    "LoginPage.tsx": "app/(auth)/login/page.tsx",
    "RegisterPage.tsx": "app/(auth)/register/page.tsx",
    "ForgotPasswordPage.tsx": "app/(auth)/forgot-password/page.tsx",
    "ChangePasswordPage.tsx": "app/(auth)/change-password/page.tsx",
    "OtpVerifyPage.tsx": "app/(auth)/verify-otp/page.tsx",
    "LandingPage.tsx": "app/(website)/page.tsx",
    "HomePage.tsx": "app/(dashboard)/page.tsx",
    "AboutUsPage.tsx": "app/(website)/about/page.tsx",
    "FaqPage.tsx": "app/(website)/faq/page.tsx",
    "SupportPage.tsx": "app/(website)/support/page.tsx",
    "TermsPage.tsx": "app/(website)/terms/page.tsx",
    "PrivacyPolicyPage.tsx": "app/(website)/privacy/page.tsx",
    "LanguagePage.tsx": "app/(website)/language/page.tsx",
    "ProfilePage.tsx": "app/(dashboard)/profile/page.tsx",
    "EditProfilePage.tsx": "app/(dashboard)/profile/edit/page.tsx",
    "MyDrawsPage.tsx": "app/(dashboard)/my-draws/page.tsx",
    "DrawDetailsPage.tsx": "app/(dashboard)/draws/[id]/page.tsx",
    "DrawResultsPage.tsx": "app/(dashboard)/results/page.tsx",
    "ParticipationDetailsPage.tsx": "app/(dashboard)/participation/[id]/page.tsx",
    "PaymentProofPage.tsx": "app/(dashboard)/payment-proof/page.tsx",
};

function convertReactRouterToNext(content) {
    let newContent = content;
    // import { ... Link ... } from 'react-router-dom' -> import Link from 'next/link'
    newContent = newContent.replace(/import\s+\{[^}]*Link[^}]*\}\s+from\s+['"]react-router-dom['"];?/g, "import Link from 'next/link';");
    // import { ... useNavigate ... } from 'react-router-dom' -> import { useRouter } from 'next/navigation'
    newContent = newContent.replace(/import\s+\{[^}]*useNavigate[^}]*\}\s+from\s+['"]react-router-dom['"];?/g, "import { useRouter } from 'next/navigation';");
    newContent = newContent.replace(/useNavigate\(\)/g, "useRouter()");
    newContent = newContent.replace(/\bnavigate\(/g, "router.push(");
    newContent = newContent.replace(/const\s+navigate\s*=\s*useRouter/g, "const router = useRouter");
    // remove remaining react-router-dom imports
    newContent = newContent.replace(/import\s+\{[^}]*\}\s+from\s+['"]react-router-dom['"];?/g, "");
    
    // Convert 'use client'
    if (newContent.includes('useRouter') && !newContent.startsWith("'use client'")) {
        newContent = "'use client';\n" + newContent;
    }
    
    return newContent;
}

if (fs.existsSync(pagesDir)) {
    const files = fs.readdirSync(pagesDir);
    files.forEach(f => {
        if (pageMap[f]) {
            const srcPath = path.join(pagesDir, f);
            const destPath = path.join(srcDir, pageMap[f]);
            let content = fs.readFileSync(srcPath, "utf8");
            content = convertReactRouterToNext(content);
            fs.writeFileSync(destPath, content, "utf8");
            fs.unlinkSync(srcPath);
        }
    });
    try {
        fs.rmdirSync(pagesDir);
    } catch(e) {}
}

const pkgPath = path.join(baseDir, "package.json");
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
pkg.scripts = {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
};
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2), "utf8");

console.log("Migration script completed successfully.");
