import os
import shutil
import glob
import re
import json

base_dir = r"c:\Users\being\Downloads\gift-box"
src_dir = os.path.join(base_dir, "src")
app_dir = os.path.join(src_dir, "app")
pages_dir = os.path.join(src_dir, "pages")

# Create structure
dirs_to_create = [
    "app/(auth)/login",
    "app/(auth)/register",
    "app/(auth)/forgot-password",
    "app/(auth)/change-password",
    "app/(auth)/verify-otp",
    "app/(website)/about",
    "app/(website)/faq",
    "app/(website)/support",
    "app/(website)/terms",
    "app/(website)/privacy",
    "app/(website)/language",
    "app/(dashboard)/profile/edit",
    "app/(dashboard)/my-draws",
    "app/(dashboard)/draws/[id]",
    "app/(dashboard)/results",
    "app/(dashboard)/participation/[id]",
    "app/(dashboard)/payment-proof",
    "app/api/auth",
    "components/ui",
    "components/shared",
    "components/forms",
    "lib",
    "utils",
    "hooks",
    "context",
    "services",
    "store",
    "types"
]

for d in dirs_to_create:
    os.makedirs(os.path.join(src_dir, d), exist_ok=True)

# Delete unnecessary files
files_to_delete = [
    "vite.config.ts",
    "index.html",
    "tsconfig.node.json",
    "tsconfig.app.json",
    os.path.join("src", "main.tsx"),
]

for f in files_to_delete:
    p = os.path.join(base_dir, f)
    if os.path.exists(p):
        os.remove(p)

# Root Layout
layout_code = """import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Gift Box App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
"""
with open(os.path.join(app_dir, "layout.tsx"), "w", encoding="utf-8") as f:
    f.write(layout_code)

# Rename index.css to globals.css and move to app
if os.path.exists(os.path.join(src_dir, "index.css")):
    shutil.move(os.path.join(src_dir, "index.css"), os.path.join(app_dir, "globals.css"))

# Pages mapping
page_map = {
    "LoginPage.tsx": "app/(auth)/login/page.tsx",
    "RegisterPage.tsx": "app/(auth)/register/page.tsx",
    "ForgotPasswordPage.tsx": "app/(auth)/forgot-password/page.tsx",
    "ChangePasswordPage.tsx": "app/(auth)/change-password/page.tsx",
    "OtpVerifyPage.tsx": "app/(auth)/verify-otp/page.tsx",
    "LandingPage.tsx": "app/(website)/page.tsx",
    "HomePage.tsx": "app/(dashboard)/page.tsx",
    "AboutUsPage.tsx": "app/(website)/about/page.tsx",
    "FaqPage.tsx": "app/(website)/faq/page.tsx",
    "SupportPage.tsx": "app/(website)/support/page.tsx",
    "TermsPage.tsx": "app/(website)/terms/page.tsx",
    "PrivacyPolicyPage.tsx": "app/(website)/privacy/page.tsx",
    "LanguagePage.tsx": "app/(website)/language/page.tsx",
    "ProfilePage.tsx": "app/(dashboard)/profile/page.tsx",
    "EditProfilePage.tsx": "app/(dashboard)/profile/edit/page.tsx",
    "MyDrawsPage.tsx": "app/(dashboard)/my-draws/page.tsx",
    "DrawDetailsPage.tsx": "app/(dashboard)/draws/[id]/page.tsx",
    "DrawResultsPage.tsx": "app/(dashboard)/results/page.tsx",
    "ParticipationDetailsPage.tsx": "app/(dashboard)/participation/[id]/page.tsx",
    "PaymentProofPage.tsx": "app/(dashboard)/payment-proof/page.tsx",
}

def convert_react_router_to_next(content):
    # This is a very basic regex replace to handle standard navigation
    # It might need manual fixing later, but automates 90% of the work.
    
    # Replace Link
    content = re.sub(r"import\s+\{[^}]*Link[^}]*\}\s+from\s+['\"]react-router-dom['\"];?", "import Link from 'next/link';", content)
    
    # Replace useNavigate with useRouter
    content = re.sub(r"import\s+\{[^}]*useNavigate[^}]*\}\s+from\s+['\"]react-router-dom['\"];?", "import { useRouter } from 'next/navigation';", content)
    content = re.sub(r"useNavigate\(\)", "useRouter()", content)
    content = re.sub(r"\bnavigate\(", "router.push(", content)
    
    # Check for navigate as a variable and rename if possible
    content = re.sub(r"const\s+navigate\s*=\s*useRouter", "const router = useRouter", content)
    
    # Other router imports (clean up react-router-dom if still there but no named exports used)
    # Just a rough cleanup
    content = re.sub(r"import\s+\{[^}]*\}\s+from\s+['\"]react-router-dom['\"];?", "", content)
    
    return content

# Move and update files
if os.path.exists(pages_dir):
    for f in os.listdir(pages_dir):
        if f in page_map:
            src_path = os.path.join(pages_dir, f)
            dest_path = os.path.join(src_dir, page_map[f])
            
            with open(src_path, "r", encoding="utf-8") as file:
                content = file.read()
            
            content = convert_react_router_to_next(content)
            
            # Write to new path
            with open(dest_path, "w", encoding="utf-8") as file:
                file.write(content)
                
            os.remove(src_path)

# Delete pages directory if empty or rename if it has left overs
if os.path.exists(pages_dir):
    try:
        os.rmdir(pages_dir)
    except OSError:
        pass # Not empty

# Update package.json scripts
pkg_path = os.path.join(base_dir, "package.json")
with open(pkg_path, "r", encoding="utf-8") as f:
    pkg = json.load(f)

pkg["scripts"] = {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
}
with open(pkg_path, "w", encoding="utf-8") as f:
    json.dump(pkg, f, indent=2)

print("Migration script completed successfully.")
